### ISSUE TITLE
Error when compiling Dutch-PostNL-Magento-2.x

### ISSUE THREAD

**Issue by phagens** [SFSF99/Dutch-PostNL-Magento-2.x#1]
Contribution works fine but when the mode of the shop is changed from development to production there is this error in de compiling of this contribution:
OOAWebstore\Orders\Controller\Adminhtml\Order\Grid
                Extra parameters passed to parent construct: $data. File: /home/jukeboxs/public_html/app/code/OOAWebstore/Orders/Controller/Adminhtml/Order/Grid.php
        OOAWebstore\Orders\Controller\Adminhtml\Order\exportOOATNTpostfCsv
                Extra parameters passed to parent construct: $data. File: /home/jukeboxs/public_html/app/code/OOAWebstore/Orders/Controller/Adminhtml/Order/exportOOATNTpostfCsv.php
        OOAWebstore\Orders\Controller\Adminhtml\Order\Index
                Extra parameters passed to parent construct: $data. File: /home/jukeboxs/public_html/app/code/OOAWebstore/Orders/Controller/Adminhtml/Order/Index.php

**Comment by SFSF99** [comment]
Meanwhile already solved for phagens. 

In development mode you don't get this warnings, in production mode you get and you have to solve this. 

$data is here a parameter already there in $contents, so $data must be removed (2x). 

E.g. before correction:

class Grid extends \Magento\Backend\App\Action
{
    protected $resultLayoutFactory;
	
    public function __construct(
            \Magento\Backend\App\Action\Context $context,
            \Magento\Framework\View\Result\LayoutFactory $resultLayoutFactory,
    		array **$data** = []
    ) {
       parent::__construct($context, **$data**);
       $this->resultLayoutFactory = $resultLayoutFactory;
    }
    public function execute()  
    {
    }
	    
}

After correction : 

class Grid extends \Magento\Backend\App\Action
{
    protected $resultLayoutFactory;
	
    public function __construct(
            \Magento\Backend\App\Action\Context $context,
            \Magento\Framework\View\Result\LayoutFactory $resultLayoutFactory
    ) {
       parent::__construct($context);
       $this->resultLayoutFactory = $resultLayoutFactory;
    }
    public function execute()  
    {
    }
	    
}
